# Generated by Django 3.2.9 on 2021-11-27 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='modified at')),
                ('deleted_at', models.DateField(auto_now=True, null=True, verbose_name='deleted at')),
                ('number', models.IntegerField(unique=True, verbose_name='number of Course')),
                ('name', models.TextField(max_length=100, verbose_name='name')),
                ('credit', models.IntegerField(verbose_name='credits')),
                ('type', models.TextField(choices=[('B', 'Basic'), ('R', 'Required'), ('O', 'Optional')], max_length=1, verbose_name='type')),
                ('course', models.SmallIntegerField(verbose_name='course')),
                ('quarter', models.SmallIntegerField(verbose_name='semestre')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='CourseEscolar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(unique=True, verbose_name='number of CourseEscolar')),
                ('start_year', models.TextField(max_length=5, verbose_name='Start year')),
                ('end_year', models.TextField(max_length=5, verbose_name='End year')),
            ],
            options={
                'verbose_name': 'CourseEscolar',
                'verbose_name_plural': 'CourseEscolar',
            },
        ),
        migrations.CreateModel(
            name='Grades',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created at')),
                ('modified_at', models.DateField(auto_now=True, verbose_name='modified at')),
                ('deleted_at', models.DateField(auto_now=True, null=True, verbose_name='deleted at')),
                ('number', models.IntegerField(unique=True, verbose_name='number of Grade')),
                ('name', models.TextField(max_length=100, verbose_name='Grade name')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(unique=True, verbose_name='number of StudentCourse')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('course_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.courseescolar')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'StudentCourse',
                'verbose_name_plural': 'StudentCourse',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.grades'),
        ),
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.teacher'),
        ),
    ]
